# Generated by Django 5.2.6 on 2025-09-05 20:48

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Датасет', max_length=100)),
                ('columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('url', models.URLField(blank=True, default='', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'модель юнит-экономики',
                'verbose_name_plural': 'модели юнит-экономики',
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Распределение', max_length=100)),
                ('description', models.CharField(blank=True, default='Описание распределения', max_length=1000, null=True)),
                ('distribution_type', models.CharField(choices=[('normal', 'Normal (Нормальное)'), ('binomial', 'Binomial (Биномиальное)'), ('poisson', 'Poisson (Пуассон)'), ('uniform', 'Uniform (Равномерное)'), ('exponential', 'Exponential (Экспоненциальное)'), ('beta', 'Beta (Бета)'), ('gamma', 'Gamma (Гамма)'), ('lognormal', 'Log-normal (Лог-нормальное)'), ('chi2', 'Chi-squared (Хи-квадрат)'), ('t', 'Student t (Стьюдента)'), ('f', 'F-distribution (Фишера)'), ('geometric', 'Geometric (Геометрическое)'), ('hypergeom', 'Hypergeometric (Гипергеометрическое)'), ('negative_binomial', 'Negative Binomial (Отрицательно биномиальное)')], default='normal', max_length=1000)),
                ('distribution_parameters', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
