# Generated by Django 4.2.23 on 2025-10-27 13:15

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ML_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Модель', max_length=100)),
                ('description', models.CharField(default='Описание модели', max_length=100)),
                ('task', models.CharField(choices=[('regression', 'Regression'), ('classification', 'Classification'), ('clusterization', 'Clusterization')], default='regression', max_length=100)),
                ('type', models.CharField(choices=[('linear_regression', 'Linear Regression'), ('polinomial_regression', 'Polinomial Regression'), ('knn_regression', 'KNN Regression'), ('gradient_boosting_regression', 'Gradient Boosting Regression'), ('logistic_regression', 'Logistic Regression'), ('support_vector_machine_classification', 'SVM Classification'), ('knn_classification', 'KNN Classification'), ('random_forest_classification', 'Random Forest Classification'), ('gradient_boosting_classification', 'Gradient Boosting Regression'), ('kmeans_clusterization', 'KMeans clusterization'), ('density_clusterization', 'Density clusterization')], default='linear', max_length=100)),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('target', models.CharField(max_length=200)),
                ('get_url', models.URLField(blank=True, default='', max_length=1000, null=True)),
                ('post_url', models.URLField(blank=True, default='', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Модель машинного обучения',
                'verbose_name_plural': 'Модели машинного обучения',
            },
        ),
    ]
