# Generated by Django 4.2.23 on 2025-10-28 19:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_algorithms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_model',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None),
        ),
    ]
